[project]
name = "dive-into-data-science"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.5",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "pandas-stubs==2.3.0.250703",
    "seaborn>=0.13.2",
]
